version: '4.0'

actions:
  generate-dataset:
    run: ehrql:v1 execute analysis/ehrql_dataset_definition.py
    outputs:
      highly_sensitive:
        output/dataset.csv: dataset

  postprocess-pregnancy-episodes:
    run: r:latest analysis/postprocess_pregnancy_episodes.R
    needs: [generate-dataset]
    outputs:
      highly_sensitive:
        output/pregnancy_episodes_processed.csv: processed

  dummy_dataset_1:
    run: r:latest analysis/dummy_definition_1.R
    outputs:
      highly_sensitive:
        output/dummy_dataset_1.csv.gz: dataset

  generate_dataset_1:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_1.py --output output/dataset_1.csv.gz --dummy-data-file output/dummy_dataset_1.csv.gz
    needs: [dummy_dataset_1]
    outputs:
      highly_sensitive:
        output/dataset_1.csv.gz: dataset
  
  dummy_dataset_2a:
    run: r:latest analysis/dummy_definition_2a.R
    outputs:
      highly_sensitive:
        output/dummy_dataset_2a.arrow: dataset

  dummy_dataset_2b:
    run: r:latest analysis/dummy_definition_2b.R
    outputs:
      highly_sensitive:
        output/dummy_dataset_2b.arrow: dataset

  dummy_dataset_2c:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_2.py --output output/dummy_dataset_2c.arrow --dummy-data-file output/dummy_dataset_2b.arrow
    needs: [dummy_dataset_2b]
    outputs:
      highly_sensitive:
        output/dummy_dataset_2c.arrow: dataset

  generate_dataset_2:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_2.py --output output/dataset_2.arrow
    outputs:
      highly_sensitive:
        output/dataset_2.arrow: dataset